kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlcloud-mysql-rbd-claim
  namespace: mlcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mlcloud-mysql
      user: mysql