kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mlcloud
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 10.199.192.16/library/mysql:5.7
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_USER
            value: mlcloud
          - name: MYSQL_PASSWORD
            value: mlcloud
          - name: MYSQL_DATABASE
            value: mlcloud
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mlcloud-mysql-rbd-claim
      - name: init-sql
        configMap:
          name: init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mlcloud
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
