apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlcloud
  labels:
    app: mlcloud
    user: mlcloud
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  cephfs:
    monitors:
    - 10.214.160.5:6789
    - 10.214.160.6:6789
    - 10.214.160.7:6789
    path: /mlcloud
    secretRef:
      name: cephfs-secret
    user: admin
  persistentVolumeReclaimPolicy: Retain
