kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlcloud
  namespace: mlcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: mlcloud
      user: mlcloud
